# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9b13f48a7bd7050a468a8266cda10c63121f250e13fa25b5aad12ad4aeff4beacc19e0486a56a2053bfa04b4221637b9f17424a378ba2add11267ad704f6c52

test:
  secret_key_base: 47c747bc7eda4710800ba8764cd2a57841c4be96383274a1ad72125ba7f86ab10ce5f36e868e69ff90d23e4ce85088769ecee0f750c0d995864a5fc6a0e4bcff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
